IKnow.Web/Models/TestViewModel.cs
namespace IKnow.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;

    public class TestViewModel
    {
        public long Id { get; set; }
        public string Name { get; set; }

        [DataType(DataType.MultilineText)] public string Description { get; set; }

        public int TimeLimit { get; set; }
        public int Views { get; set; }
        public DateTime CreationTime { get; set; }
        public DateTime EditTime { get; set; }

        [RegularExpression("^#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$",
                              ErrorMessage = "Please provide a valid background color")]
        public string HexBackground { get; set; }

        public ImageViewModel Image { get; set; }
        public long? ImageId { get; set; }

        public long? CategoryId { get; set; }
        public CategoryViewModel Category { get; set; }
        public List<QuestionViewModel> Questions { get; set; }
        public bool Deleted { get; set; }
        public bool Continue { get; set; }
        public bool Finished { get; set; }
        public int TestResult { get; set; }

        public List<QuestionViewModel> GetAvailableQuestions()
        {
            return Questions.Where(q => !q.Deleted).ToList();
        }
    }
}

IKnow.Web/Controllers/AuthController.cs
namespace IKnow.Web.Controllers
{
    using System.Threading.Tasks;
    using System.Web;
    using System.Web.Mvc;
    using BusinessLogic.DataTransferObjects;
    using BusinessLogic.Infrastructure;
    using BusinessLogic.Interfaces;
    using BusinessLogic.Services;
    using Microsoft.Owin.Security;
    using Models;

    public class AuthController : Controller
    {
        private readonly ILoggerService _logger;
        private readonly IUserService _userService;

        public AuthController(IUserService userService, ILoggerService logger)
        {
            _userService = userService;
            _logger = logger;
        }

        private IAuthenticationManager AuthenticationManager => HttpContext.GetOwinContext().Authentication;

        public ActionResult Index()
        {
            return RedirectToAction("LogIn");
        }

        public ActionResult Register()
        {
            if (User.Identity.IsAuthenticated) return RedirectToAction("Index", "Profile");

            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(AuthorizationViewModel auth, string returnUrl)
        {
            if (User.Identity.IsAuthenticated) return RedirectToAction("Index", "Profile");
            if (!ModelState.IsValid) return View(auth);

            try
            {
                var userDto = new UserDto
                              {
                                  Email = auth.Email,
                                  Password = auth.Password,
                                  Role = "user"
                              };
                await _userService.RegisterUserAsync(userDto);
                var claim = await _userService.LogInAsync(userDto);
                AuthenticationManager.SignOut();
                AuthenticationManager.SignIn(new AuthenticationProperties
                                             {
                                                 IsPersistent = true
                                             }, claim);

                _logger.Info($"New user is registered {claim.Name}");

                if (returnUrl != null)
                    return Redirect(returnUrl);
                return RedirectToAction("Index", "Profile");
            }
            catch (ServiceValidationException exception)
            {
                _logger.Error(exception.Message, exception.StackTrace);
                ModelState.AddModelError(exception.Property, exception.Message);
                return View(auth);
            }
        }

        public ActionResult LogIn()
        {
            if (User.Identity.IsAuthenticated) return RedirectToAction("Index", "Profile");

            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> LogIn(AuthorizationViewModel auth, string returnUrl)
        {
            if (User.Identity.IsAuthenticated) return RedirectToAction("Index", "Profile");
            if (!ModelState.IsValid) return View(auth);

            var userDto = new UserDto {Email = auth.Email, Password = auth.Password};
            var claim = await _userService.LogInAsync(userDto);
            if (claim == null)
            {
                _logger.Warn($"Incorrect login was detected! User {userDto.Email}");
                ModelState.AddModelError("Password", "Password or email is not correct");
            }
            else
            {
                AuthenticationManager.SignOut();
                AuthenticationManager.SignIn(new AuthenticationProperties
                                             {
                                                 IsPersistent = true
                                             }, claim);

                if (returnUrl != null)
                    return Redirect(returnUrl);

                return RedirectToAction("Index", "Profile");
            }

            return View(auth);
        }

        public ActionResult Logout()
        {
            AuthenticationManager.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

IKnow.Web/Controllers/TestsController.cs
namespace IKnow.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Threading.Tasks;
    using System.Web;
    using System.Web.Mvc;
    using AutoMapper;
    using BusinessLogic.DataTransferObjects;
    using BusinessLogic.Interfaces;
    using BusinessLogic.Services;
    using Infrastructure;
    using Models;

    public class TestsController : Controller
    {
        private readonly IImageService _imageService;
        private readonly IMapper _mapper;
        private readonly Random _random;
        private readonly IProgressService _progress;
        private readonly ITestService _testService;
        private readonly IUserService _userService;
        private readonly ICategoryService _categoryService;
        private bool _disposed;
        private readonly ILoggerService _logger;

        public TestsController(ITestService testService, IImageService imageService, IProgressService progress,
                               IUserService userService, ICategoryService categoryService, IMapper mapper, ILoggerService logger)
        {
            _random = new Random();
            _testService = testService;
            _imageService = imageService;
            _progress = progress;
            _userService = userService;
            _categoryService = categoryService;
            _mapper = mapper;
            _logger = logger;

            Categories = _mapper.Map<
                IEnumerable<CategoryDto>,
                IEnumerable<CategoryViewModel>
            >(_categoryService.GetAll());

            FilterTypes = new List<TestListFilterHelper.FilterType>
                          {
                              new TestListFilterHelper.FilterType(0, "All", test => true),
                              new TestListFilterHelper.FilterType(1, "Up to 10 min", test => test.TimeLimit <= 60 * 10),
                              new TestListFilterHelper.FilterType(2, "From 10 min to 20 min",
                                                                  test => test.TimeLimit > 60 * 10 &&
                                                                          test.TimeLimit <= 60 * 20),
                              new TestListFilterHelper.FilterType(3, "From 20 min", test => test.TimeLimit > 60 * 20),
                              new TestListFilterHelper.FilterType(4, "Finished", test =>
                                                                  {
                                                                      var allProgresses =
                                                                          _progress.GetAll(_userService
                                                                              .GetByEmail(User
                                                                                  .Identity.Name)
                                                                              .Id);

                                                                      return allProgresses.FirstOrDefault(t =>
                                                                                     t.TestId == test.Id
                                                                                 )?.Finished == true;
                                                                  })
                          };

            SortTypes = new List<TestListFilterHelper.SortType>
                        {
                            new TestListFilterHelper.SortType(0, "Popular",
                                                              (test1, test2) => test2.Views.CompareTo(test1.Views)),
                            new TestListFilterHelper.SortType(1, "New",
                                                              (test1, test2) =>
                                                                  (int) (test2.CreationTime - test1.CreationTime)
                                                                  .TotalMilliseconds),
                            new TestListFilterHelper.SortType(2, "Old",
                                                              (test1, test2) =>
                                                                  (int) (test1.CreationTime - test2.CreationTime)
                                                                  .TotalMilliseconds),
                            new TestListFilterHelper.SortType(3, "From A-Z",
                                                              (test1, test2) =>
                                                                  string.Compare(test1.Name, test2.Name,
                                                                   StringComparison.Ordinal)),
                            new TestListFilterHelper.SortType(4, "From Z-A",
                                                              (test1, test2) =>
                                                                  string.Compare(test2.Name, test1.Name,
                                                                   StringComparison.Ordinal))
                        };
        }

        private IEnumerable<CategoryViewModel> Categories { get; }
        private IEnumerable<TestListFilterHelper.FilterType> FilterTypes { get; }
        private IEnumerable<TestListFilterHelper.SortType> SortTypes { get; }

        public async Task<ActionResult> Index(TestListViewModel model)
        {
            model.CategoryTypes =
                model.CategoryTypes.Concat(Categories.Select(m => new SelectListItem
                                                                  {Text = m.Name, Value = m.Id.ToString()}));
            model.FilterTypes = FilterTypes.Select(f => (SelectListItem) f).Reverse()
                                           .Skip(User.Identity.IsAuthenticated ? 0 : 1).Reverse();
            model.SortTypes = SortTypes.Select(s => (SelectListItem) s);
            var helper = new TestListFilterHelper(FilterTypes, SortTypes);

            var allTests = string.IsNullOrWhiteSpace(model.Query)
                               ? _testService.GetAll()
                               : _testService.GetByQuery(model.Query);

            model.Tests = _mapper.Map<IEnumerable<TestDto>, IEnumerable<TestViewModel>>(
             helper.FilterAndSort(allTests, model.CategoryId, model.FilterTypeId, model.SortTypeId));

            return View(model);
        }

        public async Task<ActionResult> Open(int id)
        {
            var test = await _testService.GetByIdAsync(id);
            test.Views += 1;
            await _testService.UpdateTestAsync(test);
            var model = _mapper.Map<TestDto, TestViewModel>(test);

            var user = await _userService.GetByEmailAsync(User?.Identity?.Name);
            if (user == null) return View(model);

            var testProgress = _progress.GetAll(user.Id).FirstOrDefault(p => p.TestId == id);
            if (testProgress == null) return View(model);

            model.Continue = !testProgress.Finished;
            model.Finished = testProgress.Finished;
            if (testProgress.Finished)
                model.TestResult = testProgress.Answered.Count(a => a.Answer.IsCorrect);

            return View(model);
        }

        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Edit(int id)
        {
            var test = await _testService.GetByIdAsync(id);
            ViewBag.Categories = Categories.Select(m => new SelectListItem
                                                        {Text = m.Name, Value = m.Id.ToString()});

            return View(_mapper.Map<TestDto, TestViewModel>(test));
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Edit(TestViewModel test, HttpPostedFileBase preview)
        {
            if (!ModelState.IsValid)
                return View(test);

            if (preview != null && preview.ContentLength > 0)
            {
                try
                {
                    var randomBytes = new byte[8];
                    _random.NextBytes(randomBytes);

                    Directory.CreateDirectory(Server.MapPath("/Content/Uploaded"));

                    var path = Path.Combine("/Content/Uploaded",
                                            DateTimeOffset.Now.ToUnixTimeMilliseconds()
                                            + BitConverter.ToString(randomBytes).Replace("-", "") + "." +
                                            preview.FileName.Split('.').LastOrDefault());

                    preview.SaveAs(Server.MapPath(path));

                    test.ImageId = (await _imageService.CreateAsync(new ImageDto {Path = path})).Id;
                }
                catch (Exception ex)
                {
                    _logger.Error(ex.Message, ex.StackTrace);
                    return new HttpStatusCodeResult(500);
                }
            }
            else
            {
                var currentTestData = await _testService.GetByIdAsync(test.Id);
                test.ImageId = currentTestData.ImageId;
            }

            var testDto = _mapper.Map<TestViewModel, TestDto>(test);
            await _testService.UpdateTestAsync(testDto);

            return RedirectToAction("Open", new {testDto.Id});
        }

        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Create()
        {
            var test = new TestDto {Name = "Sample name", CreationTime = DateTime.Now, EditTime = DateTime.Now};

            var created = await _testService.CreateAsync(test);

            return RedirectToAction("Edit", new {id = created.Id});
        }
        
        [Authorize(Roles = "admin")]
        public ActionResult Delete(long? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var test = _testService.GetById((long) id);
            if (test == null) 

IKnow.Web/Views/Tests/Edit.cshtml
@model IKnow.Web.Models.TestViewModel
@{
    ViewBag.Title = "Test editor";
}

@Html.ActionLink("Go back", "Open", "Tests", new {id = Model.Id}, new {@class = "btn btn-warning m-3"})
@Html.ActionLink("Results", "AllResults", "Progress", new {testId = Model.Id}, new {@class = "btn btn-info m-3"})

<div class="container">
    @using (Html.BeginForm("Edit", "Tests", FormMethod.Post, new {enctype = "multipart/form-data"}))
    {
        @Html.AntiForgeryToken()

        <div class="p-2">
            <h4>TestViewModel</h4>
            <hr/>


            @Html.ValidationSummary(true, "", new {@class = "text-danger"})
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, new {@class = "control-label col-md-2"})
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, new {@class = "control-label col-md-2"})
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Description, new {htmlAttributes = new {@class = "form-control"}, cols = 80, rows = 10})
                    @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Category, new {@class = "control-label col-md-2"})
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.CategoryId, (IEnumerable<SelectListItem>) ViewBag.Categories, "Select category", new {htmlAttributes = new {@class = "form-control"}, cols = 80, rows = 10})
                    @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Image, new {@class = "control-label col-md-2"})
                <div class="col-md-10">
                    <input name="preview" type="file"/>
                    @Html.ValidationMessageFor(model => model.Image.Path, "", new {@class = "text-danger"})
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TimeLimit, new {@class = "control-label col-md-2"})
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TimeLimit, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.TimeLimit, "", new {@class = "text-danger"})
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HexBackground, new {@class = "control-label col-md-2"})
                <div class="col-md-10">
                    @Html.EditorFor(model => model.HexBackground, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.HexBackground, "", new {@class = "text-danger"})
                </div>
            </div>

            <div class="form-group d-none">
                @Html.LabelFor(model => model.Views, new {@class = "control-label col-md-2"})
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Views, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.Views, "", new {@class = "text-danger"})
                </div>
            </div>

            <div class="form-group d-none">
                @Html.LabelFor(model => model.CreationTime, new {@class = "control-label col-md-2"})
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreationTime, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.CreationTime, "", new {@class = "text-danger"})
                </div>
            </div>

            <div class="form-group d-none">
                @Html.LabelFor(model => model.EditTime, new {@class = "control-label col-md-2"})
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EditTime, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.EditTime, "", new {@class = "text-danger"})
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-primary"/>
                    @Html.ActionLink("Delete", "Delete", "Tests", new {id = Model.Id}, new {delete_modal = "", @class = "btn btn-danger ml-3"})
                </div>
            </div>

        </div>
    }

    <div id="myModal" class="modal fade in">
        <div class="modal-dialog">
            <div class="modal-content p-3">
                <div id="myModalContent"></div>
            </div>
        </div>
    </div>

    <div id="mySubModal" class="modal fade in">
        <div class="modal-dialog">
            <div class="modal-content p-3">
                <div id="mySubModalContent"></div>
            </div>
        </div>
    </div>


    <h3 class="p-3">Questions editor</h3>
    <div class="d-flex flex-wrap p-3">
        <div class="col-md-offset-2 col-md-10" id="replacetarget">
            @{ Html.RenderAction("Index", "Question", new {id = Model.Id}); }
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function() {
        setDeleteHandler();
    });

    function setDeleteHandler() {
        $.ajaxSetup({ cache: false });

        $("a[delete-modal]").on("click",
            function(e) {
                e.preventDefault();
                $('#myModalContent').load(this.href,
                    function() {
                        $('#myModal').modal({
                                keyboard: true
                            },
                            'show');
                        bindDeleteForm(this);
                    });
                return false;
            });
    }

    function bindDeleteForm() {
        $('form').submit(function(e) {
            e.preventDefault();
            $.ajax({
                url: this.action,
                type: this.method,
                data: $(this).serialize(),
                success: function(result) {
                    if (result.success) {
                        window.location.replace(result.url);
                    } else {
                        $('#myModalContent').html(result);
                        bindDeleteForm();
                    }
                }
            });

            return false;
        });
    }
</script>

IKnow.Web/Views/Tests/Index.cshtml
@model IKnow.Web.Models.TestListViewModel

@{
    ViewBag.Title = "Tests";
}

<div class="container">
    <div class="row">
        @if (string.IsNullOrWhiteSpace(Model.Query))
        {
            <h2 class="mt-4">All tests</h2>
        }
        else
        {
            <h2 class="mt-4">All tests that match <i>@Model.Query</i></h2>
        }
    </div>
</div>
@using (Html.BeginForm("Index", "Tests", FormMethod.Get, new {novalidate = true}))
{
    <div class="container d-flex justify-content-between">

        <div class="d-flex">
            @Html.DropDownListFor(m => m.CategoryId, Model.CategoryTypes, new {@class = "custom-select mr-1", id = "CategorySelect"})
            @Html.DropDownListFor(m => m.FilterTypeId, Model.FilterTypes, new {@class = "custom-select", id = "FilterSelect"})
        </div>
        <div class="d-flex">
            @Html.DropDownListFor(m => m.SortTypeId, Model.SortTypes, new {@class = "custom-select", id = "SortSelect"})
            @if (User.IsInRole("admin"))
            {
                @Html.ActionLink("Categories", "Index", "Category", null, new {@class = "btn btn-info ml-1"})
                @Html.ActionLink("Create", "Create", "Tests", new {@class = "btn btn-success ml-1"})
            }
        </div>
    </div>
}

@{
    Html.RenderPartial("_TestsList", Model.Tests);
}

<script>
    $("#FilterSelect, #SortSelect, #CategorySelect").change(function(e) {
        $(this).closest('form').submit();
    });
</script>

IKnow.Web/Views/Tests/Open.cshtml
@model IKnow.Web.Models.TestViewModel
@{
    ViewBag.Title = "Test";
}

@using (Html.BeginForm("Start", "Progress"))
{
    <div class="test-page" style="background-color: @Model.HexBackground">

        @Html.ActionLink(" ", "Index", null, new {@class = "close"})

        <div class="container">
            <div class="row">
                <div class="col-12">
                    <img class="preview" src="@(Model.Image?.Path)" alt="@(Model.Name)" title="" itemprop="image">
                </div>
            </div>
            <div class="row">
                <div class="col-12 text-center pt-3">
                    <h3>@(Model.Name)</h3>
                </div>
            </div>

            @if (!Model.Finished)
            {
                <div class="row">
                    <div class="col-12 text-center pt-3">
                        <h4>@(Model.GetAvailableQuestions().Count) question(s)</h4>
                    </div>
                </div>
                if (Model.TimeLimit != 0)
                {
                    <div class="row">
                        <div class="col-12 text-center pt-3">
                            <h5>This test has time limit!</h5>
                            <h6>@(TimeSpan.FromSeconds(Model.TimeLimit).ToString(@"hh\:mm\:ss"))</h6>
                        </div>
                    </div>
                }
                <div class="row justify-content-center align-items-center">
                    @if (User.Identity.IsAuthenticated)
                    {
                        @Html.ActionLink(Model.Continue ? "Continue" : "Start test", "Start", "Progress", new {Model.Id}, new {@class = "btn btn-success ml-1", data_modal = ""})
                    }
                    else
                    {
                        @Html.ActionLink("Login to start", "Login", "Auth", new {ReturnUrl = Url.Action("Open", "Tests", new {Model.Id})}, new {@class = "btn btn-primary"})
                    }

                    @if (User.IsInRole("admin"))
                    {
                        @Html.ActionLink("Edit", "Edit", new {Model.Id}, new {@class = "btn btn-info ml-1"})
                    }
                </div>

                <div class="row pt-3">
                    <p class="multiline">@(Model.Description)</p>
                </div>
            }
            else
            {
                <div class="row justify-content-center align-items-center">
                    <h6>You finished this test with result @(Model.TestResult)/@(Model.GetAvailableQuestions().Count)</h6>
                </div>
                if (User.IsInRole("admin"))
                {
                    <div class="row justify-content-center align-items-center">

                        @Html.ActionLink("Edit", "Edit", new {Model.Id}, new {@class = "btn btn-info ml-1"})
                    </div>
                }
            }

        </div>

    </div>
}

<script type="text/javascript">
    $(function() {
        setQuestionHandler();
    });

    function setQuestionHandler() {
        $.ajaxSetup({ cache: false });

        $("a[data-modal]").on("click",
            function(e) {
                e.preventDefault();
                $('body').show().load(this.href,
                    function() {
                        bindQuestion();
                    });
                return false;
            });
    }

    function bindQuestion() {
        $('.question-form').submit(function(e) {
            e.preventDefault();
            $.ajax({
                url: this.action,
                type: this.method,
                data: $(this).serialize(),
                success: function(result) {
                    $('body').html(result);
                    bindQuestion();
                }
            });
            return false;
        });
    }
</script>

IKnow.Web/Views/Tests/_Delete.cshtml
@model IKnow.Web.Models.TestViewModel

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Test</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <button class="btn modal-cancel" type="button" data-dismiss="modal">No</button>
            <input class="btn btn-danger modal-submit" type="submit" value="Yes"/>
        </div>
    }
</div>

IKnow.Web/Views/Tests/_TestsList.cshtml
@using IKnow.Web.Models
@model IEnumerable<IKnow.Web.Models.TestViewModel>

@helper RenderCard(TestViewModel model)
{
    if (model != null)
    {
        <a class="test-card" href="@Url.Action("Open", "Tests", new {model.Id})">
            <span class="content">
                <img class="preview" src="@(model?.Image?.Path)" alt="@(model.Name)" title="">
                <span class="title">@(model.Name)</span>
            </span>
        </a>
    }
}

<div class="container pt-4 pb-4">
    @if (Model?.Count() == 0)
    {
        <h5 class="text-center w-100">
            Unfortunately, we didn't find anything
        </h5>
    }
    @for (var i = 0; i < Model?.Count(); i++)
    {
        <div class="row">
            <div class="col-12 col-sm-6">
                @RenderCard(Model.ElementAtOrDefault(i))
            </div>
            <div class="col-12 col-sm-6">
                @RenderCard(Model.ElementAtOrDefault(++i))
            </div>
        </div>
    }
</div>